### ISSUE TITLE
Integrate card price API for MTG

### ISSUE THREAD

**Issue by JaredLGillespie** [SprinkleLord/card-inventory-webapp#6]
_Integration of card price API for Magic the Gathering into front end._
- Determine API to use
  - Is Key necessary for access?
  - Throttling limit?
- Determine necessary calls required
- Implement functions for calling API

**Comment by nearlyeveryone** [comment]
planning on implementing scraping from mtgprice dot com to get card prices. going to cache prices for each type of card. cache will go stale after 6 hours for now.

gonna use the NScrape nuget package for scraping the site.
